---
# Install Logstash
- name: Install Logstash
  ansible.builtin.apt:
    deb: https://artifacts.elastic.co/downloads/logstash/logstash-{{ logstash_version | default("7.16.3") }}-amd64.deb
    state: present

# Configure Logstash
- name: Data directory
  ansible.builtin.file:
    dest: /usr/share/logstash/data
    owner: logstash
    group: logstash
    recurse: yes

- name: Log directory
  ansible.builtin.file:
    src: /var/log/logstash
    dest: /usr/share/logstash/logs
    state: link

- name: Configure Logstash
  ansible.builtin.template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml
    owner: root
    group: logstash
    mode: "0660"

- name: Configure Logstash-Filters
  ansible.builtin.template:
    src: filter.conf.j2
    dest: /etc/logstash/conf.d/filter.conf
    owner: logstash
    group: logstash
    mode: "0660"
  tags:
    - config

- name: Configure Logstash-Input-Sources
  ansible.builtin.template:
    src: input.conf.j2
    dest: /etc/logstash/conf.d/input.conf
    owner: logstash
    group: logstash
    mode: "0660"
  tags:
    - config

- name: Configure Logstash-Output-Sources
  ansible.builtin.template:
    src: output.conf.j2
    dest: /etc/logstash/conf.d/output.conf
    owner: logstash
    group: logstash
    mode: "0660"
  tags:
    - config

- name: Restart Logstash
  ansible.builtin.service:
    name: logstash
    state: restarted
    enabled: yes
  tags:
    - config
    - patch
