---
# Kibana Configuration

- name: Log Elasticsearch Queries
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?elasticsearch\\.logQueries"
    line: "elasticsearch.logQueries: true"
  when:
    - kibana_log_queries
  tags:
    - config

- name: Disable Elasticsearch Queries
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?elasticsearch\\.logQueries"
    line: "elasticsearch.logQueries: false"
  when:
    - not kibana_log_queries
  tags:
    - config

- name: Non-Quiet logging
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?logging\\.quiet"
    line: "logging.quiet: false"
  when:
    - not kibana_log_quiet
  tags:
    - config

- name: Verbose logging
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?logging\\.verbose"
    line: "logging.verbose: true"
  when:
    - not kibana_log_quiet
  tags:
    - config

- name: Quiet logging
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?logging\\.quiet"
    line: "logging.quiet: true"
  when:
    - kibana_log_quiet
  tags:
    - config

- name: Non-Verbose logging
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regex: "^#?logging\\.verbose"
    line: "logging.verbose: false"
  when:
    - kibana_log_quiet
  tags:
    - config

- name: Restart Kibana
  ansible.builtin.service:
    name: kibana
    state: restarted
    enabled: yes
  tags:
    - config
