---
# Configure Logstash

- name: Configure Logstash-Filters
  ansible.builtin.template:
    src: filter.conf.j2
    dest: /etc/logstash/conf.d/filter.conf
    owner: logstash
    group: logstash
    mode: "0640"
  tags:
    - config

- name: Configure Logstash-Input-Sources
  ansible.builtin.template:
    src: input.conf.j2
    dest: /etc/logstash/conf.d/input.conf
    owner: logstash
    group: logstash
    mode: "0640"
  tags:
    - config

- name: Configure Logstash-Output-Sources
  ansible.builtin.template:
    src: output.conf.j2
    dest: /etc/logstash/conf.d/output.conf
    owner: logstash
    group: logstash
    mode: "0640"
  tags:
    - config

- name: Patch Logstash for Elastic-OSS
  replace:
    path: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb
    regexp: "build_flavor[^'|]+'default'"
    replace: "build_flavor != 'oss'"
  tags:
    - patch
    - config

- name: Restart logstash
  ansible.builtin.service:
    name: logstash
    state: restarted
    enabled: yes
  tags:
    - config
    - patch
